"""create explanation and source tables

Revision ID: acd9bdc17672
Revises: 0fbdd5759c99
Create Date: 2026-07-07 01:18:22.209307

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "acd9bdc17672"
down_revision: str | Sequence[str] | None = "0fbdd5759c99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("credibility_score", sa.Float(), nullable=True),
        sa.Column("bias_label", sa.String(length=100), nullable=True),
        sa.Column("factuality_label", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_domain"), "sources", ["domain"], unique=True)
    op.create_table(
        "explanations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("feature", sa.String(length=255), nullable=False),
        sa.Column("impact", sa.String(length=50), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("explanations")
    op.drop_index(op.f("ix_sources_domain"), table_name="sources")
    op.drop_table("sources")
    # ### end Alembic commands ###
